### ISSUE TITLE
rake snorby:setup error - "cannot load such file -- dm-rails/railtie"

### ISSUE THREAD

**Issue by user98765** [Snorby/snorby#355]
Hello. I installed snorby according to the instructions at snorby.org, but when I run the command

RAILS_ENV=production bundle exec rake snorby:setup

I get the following error:

rake aborted!
cannot load such file -- dm-rails/railtie

I ran gem list --local to verify that dm-rails is installed on my system. Version issue maybe?? Not quite sure how to troubleshoot...
 My system details: a Raspberry Pi running Raspbian. Thanks in advance!

**Comment by 0xicl33n** [comment]
Same issue on arm with debian wheezy....

root@onionpi[/v/w/snorby:master*]$bundle exec rake snorby:setup --trace
rake aborted!
cannot load such file -- dm-rails/railtie
/var/www/snorby/config/application.rb:5:in `require'
/var/www/snorby/config/application.rb:5:in `<top (required)>'
/var/www/snorby/Rakefile:4:in `require'
/var/www/snorby/Rakefile:4:in `<top (required)>'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/var/www/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/var/www/snorby/vendor/cache/ruby/1.9.1/bin/rake:23:in `load'
/var/www/snorby/vendor/cache/ruby/1.9.1/bin/rake:23:in `<main>'

root@onionpi[/v/w/snorby:master*]$gem list --local

*** LOCAL GEMS ***

actionmailer (4.2.0)
actionpack (4.2.0, 3.2.21)
actionview (4.2.0)
activejob (4.2.0)
activemodel (4.2.0, 3.2.21)
activerecord (4.2.0)
activesupport (4.2.0, 3.2.21)
addressable (2.3.7)
arel (6.0.0)
builder (3.2.2, 3.0.4)
bundler (1.8.3)
dm-active_model (1.2.1)
dm-core (1.2.1)
dm-rails (1.2.1)
erubis (2.7.0)
globalid (0.3.3)
hike (1.2.3)
i18n (0.7.0)
journey (1.0.4)
json (1.8.2)
loofah (2.0.1)
mail (2.6.3)
mime-types (2.4.3)
mini_portile (0.6.2)
minitest (5.5.1)
multi_json (1.11.0)
nokogiri (1.6.6.2)
rack (1.6.0, 1.4.5)
rack-cache (1.2)
rack-ssl (1.3.4)
rack-test (0.6.3)
rails (4.2.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
railties (4.2.0, 3.2.21)
rake (10.4.2)
rdoc (3.12.2)
sprockets (2.12.3, 2.2.3)
sprockets-rails (2.2.4)
thor (0.19.1)
thread_safe (0.3.4)
tilt (1.4.1)
tzinfo (1.2.2)

root@onionpi[/v/w/snorby:master*]$ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [arm-linux-eabihf]


There has to be a fix for this...

**Comment by mandrake74** [comment]
The same here. I think it's the first time I could not resolve such issue by myself if not finding it on Internet.
Good way to learn how a ruby system should work tough...
I think I have tried everything at a system level on a debian wheezy. 
Since it was not working with debian 1.9.3 apt packages, I have installed it from source but I have ended with exact same error. 
I have also tried with a fresh ruby 2.2.1 install and with the latest rails version, but if failed again (with a different error message). I have then figured out that ruby 2.x versions are not supported by Snorby (or at least it is what I have read on the web).
I am pulling the last version from git master, so I would really appreciate to have some help here. It looks like plenty of people are experiencing the same issue without any response.
Simplicity you said? I must be very dumb then..thanks for your help!

**Comment by mandrake74** [comment]
Hi, it looks like posting here as a last chance gave me finally the clue of what was wrong! Thanks Github god! ;-)

Having a second look to the gem list diff between mine and @0xicl33n, and seen some similar issues with other rails applications involving bundler, I have just installed the following gems specific versions for bundler and dm-rails:
gem install dm-rails -v 1.2.1
gem install bundler -v 1.2.1

And now it works, with: bundle exec rake snorby:setup

I just don't know why these versions are not installed by default using the Gemfile provided in the snorby git, might worth to update this Gemfile with these versions to make it work out of the box.

Hope this will help other people who where desperately trying to make snorby working on a debian wheezy (actually I'm using a kali 1.0.9 distro).

Cheers, Mdk
