### ISSUE TITLE
cant start snorby

### ISSUE THREAD

**Issue by avcherkasov** [Snorby/snorby#390]
Hi everyone.
I cant start snorby,
```/etc/init.d/snorby start
starting /etc/init.d/snorby...
nohup: appending output to `nohup.out'
Jammit Warning: Asset compression disabled -- Java unavailable.
/usr/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 55, col 0: `test:' (ArgumentError)
        from /usr/lib/ruby/1.9.1/syck.rb:135:in `load'
        from /var/www/snorby/config/application.rb:39:in `<module:Snorby>'
        from /var/www/snorby/config/application.rb:14:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/www/snorby/config/environment.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from script/delayed_job:3:in `<main>'
```
How can I understand where is bad YAML?
init.d looks like
```  start)
    echo "starting $0..."
    cd /var/www/snorby && nohup rails server -e -d production &
    cd /var/www/snorby && /usr/bin/ruby script/delayed_job start
    cd /var/www/snorby && /usr/local/bin/rails runner 'Snorby::Jobs::SensorCacheJob.new(false).perform; Snorby::Jobs::DailyCacheJob.new(false).perform'
    echo -e "done."
    exit 0
```

**Comment by frconil** [comment]
It might be in your database config.

What does it look like?
