### ISSUE TITLE
Snorby 2.6.3 broken with authentication_mode: database

### ISSUE THREAD

**Issue by oztiks** [Snorby/snorby#402]
It appears Snorby 2.6.3 is broken and generates incomplete SQL statements. After attempting to upgrade to it, I get constantly SQL syntax errors against MariaDB and MySQL:

```
[snorby@X log]$ tail -f production.log

Started POST "/users/login" for X at 2015-12-07 14:22:44 -0500
  Processing by SessionsController#create as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"REMOVED", "user"=>{"email"=>"REMOVED", "password"=>"[FILTERED]", "remember_me"=>"1"}}
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' LIMIT 1' at line 1 (code: 1064, sql state: 42000, query: SELECT `id`, `email`, `encrypted_password`, `remember_token`, `remember_created_at`, `reset_password_token`, `sign_in_count`, `current_sign_in_at`, `last_sign_in_at`, `current_sign_in_ip`, `last_sign_in_ip`, `favorites_count`, `accept_notes`, `notes_count`, `per_page_count`, `admin`, `enabled`, `gravatar`, `created_at`, `updated_at`, `online`, `last_daily_report_at`, `last_weekly_report_at`, `last_monthly_report_at`, `last_email_report_at`, `email_reports` FROM `users` WHERE `email` = ' LIMIT 1, uri: mysql:root@localhostsnorby?adapter=mysql&username[REMOVED])
Completed 500 Internal Server Error in 48ms

DataObjects::SQLError (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' LIMIT 1' at line 1):
  app/controllers/application_controller.rb:37:in `user_setup'
```

There seem to be a variety of other errors too related to scheduled tasks. It appears there is a SQL syntax error somewhere in the new code.

Originally I thought this was a mysql 5.7.9 issue as well, but after moving to MariaDB and older versions of MySQL it appears to be related to Snorby 2.6.3.

**Comment by Gigithecode** [comment]
I can confirm that;
I cannot create the snorby database with Snorby 2.6.3 - for use with snort and barnyard2
DataObjects::SQLError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' at line 1
/var/lib/gems/2.3.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:34:in `execute_reader
....
....

Do you have any workaround? I'm stuck on it!
Regards,
Guillaume
