### ISSUE TITLE
rake aborted! undefined method `name' for ["AST4ADT", "SystemV", "posix", "zoneinfo", "share", "usr"]:Array

### ISSUE THREAD

**Issue by mmamun1** [Snorby/snorby#419]
rake aborted!
undefined method `name' for ["AST4ADT", "SystemV", "posix", "zoneinfo", "share", "usr"]:Array
/var/www/html/snorby/config/application.rb:84:in `<class:Application>'
/var/www/html/snorby/config/application.rb:46:in `<module:Snorby>'
/var/www/html/snorby/config/application.rb:14:in `<top (required)>'
/var/www/html/snorby/Rakefile:4:in `require'
/var/www/html/snorby/Rakefile:4:in `<top (required)>'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/bin/rake:23:in `load'
/var/www/html/snorby/vendor/cache/ruby/1.9.1/bin/rake:23:in `<main>'

**Comment by jchisholm59** [comment]
I wonder is anyone is looking into this. Snorby on Ubuntu 14.04 seems completely broken.

**Comment by jchisholm59** [comment]
Is this project dead?

**Comment by squarism** [comment]
@jchisholm59: Snorby domain is gone.  Seems like it, idk really, i did find this usenet post though.  He's doing a rewrite in Go. Which would be cool because have to maintain Ruby 1.9.3 at work just for Snorby.  https://groups.google.com/forum/#!topic/snorby/oxxZsZoXA0A
