### ISSUE TITLE
Installation on Raspberry PI

### ISSUE THREAD

**Issue by fabricioit** [Snorby/snorby#451]
Trying to install Snorby on raspberry pi 2 after a lot of errors i'm here to ask help to gurus, i tried a lot of times to install always with errors, now i'm on the step rake snorby:setup after done  "bundle install --no-deployment".
My system is raspbian jessie and get those errors running "rake snorby:setup":

/root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- rake (LoadError)
        from /root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /root/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/rake-0.9.2.2/bin/rake:30:in `<top (required)>'
        from /root/.rbenv/versions/2.3.1/bin/rake:23:in `load'
        from /root/.rbenv/versions/2.3.1/bin/rake:23:in `<main>'

**Comment by justinglock40** [comment]
Same for me
