### ISSUE TITLE
snorby webGUI: something went wrong

### ISSUE THREAD

**Issue by mrglobule** [Snorby/snorby#452]
Good morning everybody,
i wrote this issue because i need your help.
I set up snorby yesterday and all is working; but now i have an error web page instead of my snorby.

```
Error:

   Web application could not be started

Error ID:

   ed497c8b

Details:

(<unknown>): did not find expected key while parsing a block mapping at line 10 column 3 (Psych::SyntaxError)
  /usr/local/lib/ruby/2.3.0/psych.rb:377:in `parseʼ
  /usr/local/lib/ruby/2.3.0/psych.rb:377:in `parse_streamʼ
  /usr/local/lib/ruby/2.3.0/psych.rb:325:in `parseʼ
  /usr/local/lib/ruby/2.3.0/psych.rb:252:in `loadʼ
  /var/www/snorby/config/application.rb:39:in `<module:Snorby>ʼ
  /var/www/snorby/config/application.rb:14:in `<top (required)>ʼ
  /var/www/snorby/config/environment.rb:2:in `requireʼ
  /var/www/snorby/config/environment.rb:2:in `<top (required)>ʼ
  config.ru:3:in `requireʼ
  config.ru:3:in `block in <main>ʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_evalʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initializeʼ
  config.ru:1:in `newʼ
  config.ru:1:in `<main>ʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.1/src/helper-scripts/rack-preloader.rb:110:in `evalʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.1/src/helper-scripts/rack-preloader.rb:110:in `preload_appʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.1/src/helper-scripts/rack-preloader.rb:156:in `<module:App>ʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.1/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>ʼ
  /usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.1.1/src/helper-scripts/rack-preloader.rb:29:in `<main>ʼ

System information:

   Application root
          /var/www/snorby

   Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
          production

```
Can you help me to restart snorby?
Thanks in advance.
Regards,

**Comment by mrglobule** [comment]
I found that the comments are the problem in the snorby_conf.yml.

I edit this file and delete all the comments and all is OK.
