### ISSUE TITLE
Error: bundle exec rake --trace  snorby:setup  

### ISSUE THREAD

**Issue by solower** [Snorby/snorby#466]
blackey@blackey-virtual-machine:~/Desktop/snorby$ bundle exec rake --trace  snorby:setup
rake aborted!
There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `*'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `days'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/devise-1.5.4/lib/devise.rb:121:in `<module:Devise>'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/devise-1.5.4/lib/devise.rb:8:in `<top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/home/blackey/Desktop/snorby/config/application.rb:12:in `<top (required)>'
/home/blackey/Desktop/snorby/Rakefile:4:in `require'
/home/blackey/Desktop/snorby/Rakefile:4:in `<top (required)>'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/bin/rake:22:in `load'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/bin/rake:22:in `<top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/home/blackey/Desktop/snorby/config/application.rb:12:in `<top (required)>'
/home/blackey/Desktop/snorby/Rakefile:4:in `require'
/home/blackey/Desktop/snorby/Rakefile:4:in `<top (required)>'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/bin/rake:22:in `load'
/home/blackey/Desktop/snorby/vendor/cache/ruby/2.4.0/bin/rake:22:in `<top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/blackey/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/blackey/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jkellogg90** [comment]
I had the same issue. I had to install Ruby 2.3.3 (rbenv install 2.3.3). While in the Snorby directory, run rbenv local 2.3.3. Also run the following in the Snorby directory. Some of this might be unnecessary. I was also troubleshooting this at the time but this worked for me. 

rm -rf .bundle/
rm -rf vendor/cache/
rm -rf Gemfile.lock
gem install bundler --no-ri --no-rdoc
bundle install 
gem install dm-zone-types -v '0.3'   (This was missing for me)
bundle install 
bundle exec rake snorby:setup --trace

**Comment by tonybreak** [comment]
i have the same problem.
`# bundle exec rake snorby:setup --trace
rake aborted!
There was an error while trying to load the gem 'devise'.
Gem Load Error is: ActiveSupport::Duration can't be coerced into Integer
Backtrace for gem load error is:
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `*'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:50:in `days'
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/core_ext/numeric/time.rb:55:in `weeks'
/usr/local/lib/ruby/gems/2.4.0/gems/devise-1.5.4/lib/devise.rb:121:in `<module:Devise>'
/usr/local/lib/ruby/gems/2.4.0/gems/devise-1.5.4/lib/devise.rb:8:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/opt/snorby/config/application.rb:12:in `<top (required)>'
/opt/snorby/Rakefile:4:in `require'
/opt/snorby/Rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Bundler Error Backtrace:
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/opt/snorby/config/application.rb:12:in `<top (required)>'
/opt/snorby/Rakefile:4:in `require'
/opt/snorby/Rakefile:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'`


And I don't know how to fix it~ Hope help.

**Comment by SrijanNandi** [comment]
Same issue. Was anyone able to figure this out....

bundle exec rake snorby:setup --trace
rake aborted!
cannot load such file -- responders
/var/lib/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/2.4.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/2.4.0/gems/devise-4.2.0/lib/devise.rb:7:in `<top (required)>'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `block (2 levels) in require'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler.rb:114:in `require'
/opt/snorby/config/application.rb:12:in `<top (required)>'
/opt/snorby/Rakefile:4:in `require'
/opt/snorby/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/lib/gems/2.4.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/var/lib/gems/2.4.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

**Comment by Whasley** [comment]
I'm trying to run the snorby with suricata ids in Ubuntu 18.04. The Suricata is working fine, just missing the logs on a dashboard (Snorby). But when I try to do **bundle exec rake snorby: setup --trace**
 I get the error below ...

/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-3.2.22/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
rake aborted!
undefined method `yaml_as' for Module:Class
Did you mean?  yaml_tag
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/delayed_job-2.1.4/lib/delayed/yaml_ext.rb:8:in `<class:Module>'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/delayed_job-2.1.4/lib/delayed/yaml_ext.rb:7:in `<top (required)>'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/delayed_job-2.1.4/lib/delayed_job.rb:6:in `<top (required)>'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
/root/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
/var/www/html/snorby/config/application.rb:12:in `<top (required)>'
/var/www/html/snorby/Rakefile:4:in `require'
/var/www/html/snorby/Rakefile:4:in `<top (required)>'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/root/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/root/.rbenv/versions/2.6.1/bin/rake:23:in `load'
/root/.rbenv/versions/2.6.1/bin/rake:23:in `<main>'
/root/.rbenv/versions/2.6.1/bin/ruby_executable_hooks:24:in `eval'
/root/.rbenv/versions/2.6.1/bin/ruby_executable_hooks:24:in `<main>'
