### ISSUE TITLE
The pdfkit not installing wkhtmltopdf - wrong link to archive

### ISSUE THREAD

**Issue by nan008** [Snorby/snorby#468]
Hello,

I am getting the error while executing the pdfkit --install-wkhtmltopdf

First getting this error 
```
/root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit:9:in `detect_architecture': uninitialized constant Config (NameError)
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit:56:in `block (2 levels) in <top (required)>'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1396:in `call'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1396:in `block in parse_in_order'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit:72:in `<top (required)>'
	from /root/.rbenv/versions/2.2.2/bin/pdfkit:23:in `load'
	from /root/.rbenv/versions/2.2.2/bin/pdfkit:23:in `<main>'
```
but then correcting Config to RbConfig in /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit is getting me this error:

```
/root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop': redirection forbidden: http://code.google.com/p/wkhtmltopdf/downloads/list -> https://code.google.com/archive/p/wkhtmltopdf/downloads (RuntimeError)
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit:27:in `download_wkhtmltopdf'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit:62:in `block (2 levels) in <top (required)>'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1396:in `call'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1396:in `block in parse_in_order'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
	from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
	from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pdfkit-0.4.6/bin/pdfkit:72:in `<top (required)>'
	from /root/.rbenv/versions/2.2.2/bin/pdfkit:23:in `load'
	from /root/.rbenv/versions/2.2.2/bin/pdfkit:23:in `<main>'
```

I checked the link and it is not working anymore as the archive was removed

```
wkhtmltopdf has Moved!

This project has moved to a new location on the internet. Its new home is at:
http://wkhtmltopdf.org
```

Can I proceed with the setup without it?

**Comment by gehrhorn** [comment]
You can, but some of the reports may not work. If you send a pull request I can merge it.
