### ISSUE TITLE
/var/lib/gems/2.3.0/gems/pdfkit-0.4.6/bin/pdfkit:9:in `detect_architecture': uninitialized constant Config (NameError)

### ISSUE THREAD

**Issue by Abbed** [Snorby/snorby#470]
while building snorby after typing "pdfkit --install-wkhtmltopdf"

I get:

/var/lib/gems/2.3.0/gems/pdfkit-0.4.6/bin/pdfkit:9:in `detect_architecture': uninitialized constant Config (NameError)
Did you mean?  RbConfig
	from /var/lib/gems/2.3.0/gems/pdfkit-0.4.6/bin/pdfkit:56:in `block (2 levels) in <top (required)>'
	from /usr/lib/ruby/2.3.0/optparse.rb:1540:in `block in parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
	from /usr/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1613:in `permute!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1635:in `parse!'
	from /var/lib/gems/2.3.0/gems/pdfkit-0.4.6/bin/pdfkit:72:in `<top (required)>'
	from /usr/local/bin/pdfkit:23:in `load'
	from /usr/local/bin/pdfkit:23:in `<main>'

I'm running xubuntu 16.04.2 LTS

**Comment by QuentinIUT** [comment]
Nearly the same here on CentOS. Instead of that command, just browse through your packet repository. On CentOS I've found a version of this software which allow me to avoid recompiling sources with all the uncertainty that comes along. Snorby happily accept it even if it's not the proper way to get it.

**Comment by nan008** [comment]
I had the same problem on Centos and gave up installing it with pdfkit

I installed gem wkhtmltopdf and then got the wkhtmltopdf from:

 wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
tar xvJf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz 
sudo cp wkhtmltox/bin/wkhtmlto* /usr/bin/
and changed the path in snorby_config.yml to point to this version and it is working without this dready pdfkit command

Hope it helps
