### ISSUE TITLE
Error while loading `delayed_job_data_mapper.gemspec`: undefined method `today' for Date:Class. Bundler cannot continue

### ISSUE THREAD

**Issue by leandropc** [Snorby/snorby#485]
Hi, I'm having trouble to update Snorby. Notice that I recently update to the ruby version 2.0.0. 

Any clues? 

```
root@snorby:/var/www/snorby# rake snorby:update --trace
rake aborted!

[!] There was an error while loading `delayed_job_data_mapper.gemspec`: undefined method `today' for Date:Class. Bundler cannot continue.

 #  from /var/www/snorby/vender/cache/ruby/2.0.0/bundler/gems/delayed_job_data_mapper-6f1c4a8c3ad6/delayed_job_data_mapper.gemspec:8
 #  -------------------------------------------
 #    s.authors           = 'Brandon Keepers'
 >    s.date              = Date.today.to_s
 #    s.email             = 'brandon@collectiveidea.com'
 #  -------------------------------------------
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler.rb:508:in `rescue in eval_gemspec'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler.rb:500:in `eval_gemspec'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler.rb:437:in `block in load_gemspec_uncached'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/shared_helpers.rb:65:in `chdir'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/shared_helpers.rb:65:in `block in chdir'
/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/shared_helpers.rb:64:in `chdir'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler.rb:436:in `load_gemspec_uncached'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler.rb:422:in `load_gemspec'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/path.rb:151:in `load_gemspec'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/path.rb:166:in `block in load_spec_files'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/path.rb:165:in `each'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/path.rb:165:in `load_spec_files'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/git.rb:199:in `load_spec_files'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/path.rb:100:in `local_specs'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/source/git.rb:166:in `specs'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:268:in `block (2 levels) in index'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:266:in `each'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:266:in `block in index'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/index.rb:11:in `build'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:263:in `index'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:257:in `resolve'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:170:in `specs'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:237:in `specs_for'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/definition.rb:226:in `requested_specs'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:108:in `block in definition_method'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:20:in `setup'
/var/lib/gems/2.0.0/gems/bundler-1.16.0/lib/bundler.rb:107:in `setup'
/var/www/snorby/config/boot.rb:8:in `<top (required)>'
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/www/snorby/config/application.rb:1:in `<top (required)>'
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/www/snorby/Rakefile:4:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:589:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:89:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:88:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:72:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/a
```

**Comment by leandropc** [comment]
With **bundle install** I get this

```
The dependency jruby-openssl (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency warbler (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jruby-rack-worker (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.

[!] There was an error while loading `delayed_job_data_mapper.gemspec`: undefined method `today' for Date:Class. Bundler cannot continue.

 #  from /var/www/snorby/vender/cache/ruby/2.0.0/bundler/gems/delayed_job_data_mapper-6f1c4a8c3ad6/delayed_job_data_mapper.gemspec:8
 #  -------------------------------------------
 #    s.authors           = 'Brandon Keepers'
 >    s.date              = Date.today.to_s
 #    s.email             = 'brandon@collectiveidea.com'
 #  -------------------------------------------
```

**Comment by ThreadAbort** [comment]
I ran "gem update --system"

and it fixed that issue.
