### ISSUE TITLE
Problem when installing snorby.  sudo bundle exec rake snorby:setup

### ISSUE THREAD

**Issue by c008644** [Snorby/snorby#493]
Hello all,

I am having a problem installing snorby on Ubuntu.  I have been following the guide at https://github.com/bensooter/Snort16OnUbuntu/tree/0b7d64ca5fb2bf7caab1b617732453a25607732b   modifying it as needed for Ubuntu 18.  When I get to the part of actually building Snorby I get the rake aborted error.

$ sudo bundle exec rake snorby:setup --trace
rake aborted!
undefined method `yaml_as' for Module:Class
Did you mean?  yaml_tag
/var/lib/gems/2.5.0/gems/delayed_job-2.1.4/lib/delayed/yaml_ext.rb:8:in `<class:Module>'
/var/lib/gems/2.5.0/gems/delayed_job-2.1.4/lib/delayed/yaml_ext.rb:7:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/2.5.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/2.5.0/gems/delayed_job-2.1.4/lib/delayed_job.rb:6:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:81:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:76:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:76:in `block in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:114:in `require'
/var/www/snorby/config/application.rb:12:in `<top (required)>'
/var/www/snorby/Rakefile:4:in `require'
/var/www/snorby/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/var/lib/gems/2.5.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:424:in `exec'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.5.0/gems/bundler-1.16.6/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

I am running ruby 2.5.1p57

I have been working on this for the last few weeks and cannot find the answer myself.  Any help would be appreciated.

**Comment by q2dg** [comment]
Well, it seems this project is pretty abandoned

**Comment by jkellogg90** [comment]
You want to replace the string "yaml_as" with "yaml_tag" in the files listed. 

You can also grep your ruby directory for the string yaml_as "grep -R -i yaml_as <dir>" to find any other files with the deprecated method.

This fixed the issue for me.

**Comment by ChrissT94** [comment]
jkellogg90 

> You want to replace the string "yaml_as" with "yaml_tag" in the files listed.
> 
> You can also grep your ruby directory for the string yaml_as "grep -R -i yaml_as directory" to find any other files with the deprecated method.
> 
> This fixed the issue for me.

Where are the yaml_as files located?
