### ISSUE TITLE
bundle exec rake snorby:setup - error rake aborted! invalid hash

### ISSUE THREAD

**Issue by diveshu** [Snorby/snorby#509]
While executing below command, i get the error:  rake aborted! invalid hash. Pls help
bundle exec rake snorby:setup --trace

Jammit Warning: Asset compression disabled -- Java unavailable.
No time_zone specified in snorby_config.yml; detected time_zone: Asia/Kolkata
** Invoke snorby:setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute snorby:setup
** Invoke secret (first_time)
** Execute secret
51478f8c5d35a2656e577adf695c0488526d0ab00549b4a2672fa2cf75b5ae28b1e58fa72a42ab18c6f0286c5478a722fe83e4c2d27c58cdfba29c63c2a2b034
** Invoke db:create (first_time)
** Invoke environment 
** Execute db:create
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1007 (HY000) at line 1: Can't create database 'snorby'; database exists
** Invoke snorby:update (first_time)
** Invoke environment 
** Execute snorby:update
** Invoke db:autoupgrade (first_time)
** Invoke environment 
** Execute db:autoupgrade
[datamapper] Finished auto_upgrade! for :default repository 'snorby'
** Invoke db:seed (first_time)
** Invoke environment 
** Execute db:seed
rake aborted!
invalid hash
/usr/local/lib/ruby/gems/1.9.1/gems/bcrypt-ruby-3.0.1/lib/bcrypt.rb:171:in `initialize'
/usr/local/lib/ruby/gems/1.9.1/gems/bcrypt-ruby-3.0.1/lib/bcrypt.rb:161:in `new'
/usr/local/lib/ruby/gems/1.9.1/gems/bcrypt-ruby-3.0.1/lib/bcrypt.rb:161:in `create'
/usr/local/lib/ruby/gems/1.9.1/gems/devise-1.5.4/lib/devise/models/database_authenticatable.rb:117:in `password_digest'
/usr/local/lib/ruby/gems/1.9.1/gems/devise-1.5.4/lib/devise/models/database_authenticatable.rb:35:in `password='
/usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:333:in `block in attributes='
/usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:329:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:329:in `attributes='
/usr/local/lib/ruby/gems/1.9.1/gems/dm-rails-1.2.1/lib/dm-rails/multiparameter_attributes.rb:93:in `attributes='
/usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:748:in `initialize'
/usr/local/lib/ruby/gems/1.9.1/gems/dm-validations-1.2.0/lib/dm-validations.rb:129:in `new'
/usr/local/lib/ruby/gems/1.9.1/gems/dm-validations-1.2.0/lib/dm-validations.rb:129:in `create'
/var/www/snorby/db/seeds.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:234:in `load'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:234:in `block in load'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `block in load_dependency'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:640:in `new_constants_in'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `load_dependency'
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:234:in `load'
/usr/local/lib/ruby/gems/1.9.1/gems/dm-rails-1.2.1/lib/dm-rails/railties/database.rake:55:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/var/www/snorby/lib/tasks/snorby.rake:43:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/var/www/snorby/lib/tasks/snorby.rake:33:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:seed

**Comment by diveshu** [comment]
> While executing below command, i get the error: rake aborted! invalid hash. Pls help bundle exec rake snorby:setup --trace
> 
> Jammit Warning: Asset compression disabled -- Java unavailable. No time_zone specified in snorby_config.yml; detected time_zone: Asia/Kolkata ** Invoke snorby:setup (first_time) ** Invoke environment (first_time) ** Execute environment ** Execute snorby:setup ** Invoke secret (first_time) ** Execute secret 51478f8c5d35a2656e577adf695c0488526d0ab00549b4a2672fa2cf75b5ae28b1e58fa72a42ab18c6f0286c5478a722fe83e4c2d27c58cdfba29c63c2a2b034 ** Invoke db:create (first_time) ** Invoke environment ** Execute db:create mysql: [Warning] Using a password on the command line interface can be insecure. ERROR 1007 (HY000) at line 1: Can't create database 'snorby'; database exists ** Invoke snorby:update (first_time) ** Invoke environment ** Execute snorby:update ** Invoke db:autoupgrade (first_time) ** Invoke environment ** Execute db:autoupgrade [datamapper] Finished auto_upgrade! for :default repository 'snorby' ** Invoke db:seed (first_time) ** Invoke environment ** Execute db:seed rake aborted! invalid hash /usr/local/lib/ruby/gems/1.9.1/gems/bcrypt-ruby-3.0.1/lib/bcrypt.rb:171:in `initialize' /usr/local/lib/ruby/gems/1.9.1/gems/bcrypt-ruby-3.0.1/lib/bcrypt.rb:161:in `new' /usr/local/lib/ruby/gems/1.9.1/gems/bcrypt-ruby-3.0.1/lib/bcrypt.rb:161:in `create' /usr/local/lib/ruby/gems/1.9.1/gems/devise-1.5.4/lib/devise/models/database_authenticatable.rb:117:in `password_digest' /usr/local/lib/ruby/gems/1.9.1/gems/devise-1.5.4/lib/devise/models/database_authenticatable.rb:35:in `password=' /usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:333:in `block in attributes=' /usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:329:in `each' /usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:329:in `attributes=' /usr/local/lib/ruby/gems/1.9.1/gems/dm-rails-1.2.1/lib/dm-rails/multiparameter_attributes.rb:93:in `attributes=' /usr/local/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/resource.rb:748:in `initialize' /usr/local/lib/ruby/gems/1.9.1/gems/dm-validations-1.2.0/lib/dm-validations.rb:129:in `new' /usr/local/lib/ruby/gems/1.9.1/gems/dm-validations-1.2.0/lib/dm-validations.rb:129:in `create' /var/www/snorby/db/seeds.rb:5:in `<top (required)>' /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:234:in `load' /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:234:in `block in load' /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `block in load_dependency' /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:640:in `new_constants_in' /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `load_dependency' /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:234:in `load' /usr/local/lib/ruby/gems/1.9.1/gems/dm-rails-1.2.1/lib/dm-rails/railties/database.rake:55:in `block (2 levels) in <top (required)>' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain' /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke' /var/www/snorby/lib/tasks/snorby.rake:43:in `block (2 levels) in <top (required)>' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain' /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke' /var/www/snorby/lib/tasks/snorby.rake:33:in `block (2 levels) in <top (required)>' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain' /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `each' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run' /usr/local/lib/ruby/gems/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>' /usr/local/bin/rake:23:in `load' /usr/local/bin/rake:23:in `
> 
> '
> Tasks: TOP => db:seed
