### ISSUE TITLE
FrozenError (can't modify frozen String: "")

### ISSUE THREAD

**Issue by hans-mayer** [Snorby/snorby#518]
Dear All, 

I tried to install snorby from this git repository.
My environment is: 
debian 11 bullseye - latest patch level 
8.0.32 MySQL Community Server
Apache/2.4.54 with module passenger 

ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
Rails 3.2.22
rake, version 12.3.3
gem 3.4.7 

I followed primary the instructions in this wiki about Ubuntu 11.10 

I modified Gemfile slightly because I don't use psql and add 
gem 'bigdecimal',              '1.3.0'
as version 2 brought some errors.

I created database.yml , snorby_config.yml and mail_config.rb

bundle install --deployment  runs without errors 
rake snorby:setup brings some warnings but terminates normally 

when I open my browser I see the following error: 
We're sorry, but something went wrong......

In log/production.log there is 

Started GET "/" for 192.168.241.29 at 2023-03-05 18:24:47 +0100
Processing by PageController#dashboard as HTML
Completed 500 Internal Server Error in 0.4ms

FrozenError (can't modify frozen String: ""):
  app/controllers/application_controller.rb:33:in `user_setup'

This is the part
     31     def user_setup
     32 
     33       @snorby_url ||= root_url(:host => Snorby::CONFIG[:domain])
     34 

in log/development.log there are a lot of SQL statements smaller 0.5 ms

The same when I run: rails server 
and open a browser at port 3000

I tried to use MySQL version 5.7 in a docker but "snorby:setup" tries to connect to a socket which I don't have in the docker environment. 

Some ideas what I can do ? 
Any help is welcome. 

Is there a user forum where people can exchange information ? 

Kind regards 
Hans 

--

**Comment by thsalex** [comment]
Hi guys!
I have the same problem

Processing by PageController#dashboard as HTML
Completed 500 Internal Server Error in 0.3ms

FrozenError (can't modify frozen String: ""):
  app/controllers/application_controller.rb:33:in `user_setup'

Anyone help-me?

Thank's

**Comment by viperjet** [comment]
Hey Team.

Same problem here like thsalex.

**Comment by hans-mayer** [comment]
I believe we are riding a dead horse. 
Last updates are years ago. 

// Hans

**Comment by viperjet** [comment]
I see no alternative so far. Just startet with snort 2.9 on Debian 11 and want to get it running. There must be a fix for that simple error. The cause is a empty url variable i guess.

**Comment by hans-mayer** [comment]
I managed several commercial firewalls and WAFs during the last decades. My impression there are a lot of great open source projects, but related to security there is nothing useful. Btw, snort seems to be dead too.
